[package]
name = "VerdictChain"
version = "1.0.0"
authors = ["VerdictChain Team"]

[addresses]
VerdictChain = "0xb4fa8f8edc3210feb00d0e9df7f74cc230b9499a7747e0097d7cf0ce2e49192b"

[dev-addresses]
VerdictChain = "0xb4fa8f8edc3210feb00d0e9df7f74cc230b9499a7747e0097d7cf0ce2e49192b"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
