[package]
name = "VerdictChain"
version = "1.0.0"
authors = ["VerdictChain Team"]

[addresses]
VerdictChain = "0x676f3dbd31a1189093019f5723c1a0c07b23766f79410547d55d9cbbeeeca99f"

[dev-addresses]
VerdictChain = "0x676f3dbd31a1189093019f5723c1a0c07b23766f79410547d55d9cbbeeeca99f"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
