[package]
name = "VerdictChain"
version = "1.0.0"
authors = ["VerdictChain Team"]

[addresses]
VerdictChain = "0xf96d929adc9b08c8be97d07acd65c44e779b96c45371cf25943c934523dd960a"

[dev-addresses]
VerdictChain = "0xf96d929adc9b08c8be97d07acd65c44e779b96c45371cf25943c934523dd960a"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
